name: findany_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_messaging_web: ^3.9.4
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  firebase_in_app_messaging: ^0.8.0+11


  #chatting
  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2

  #Notification
  flutter_local_notifications: ^17.2.2


  google_sign_in: ^6.2.1
  flutter_easyloading: ^3.0.5
  file_picker: ^7.1.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  gsheets: ^0.5.0
  flutter_secure_storage: ^9.2.1
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  flutter_cache_manager: ^3.3.1
  in_app_update: ^4.2.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  rxdart: ^0.28.0
  async: ^2.11.0
  http: ^1.2.1
  razorpay_flutter: ^1.3.7
  path: ^1.9.0
  google_maps_flutter: ^2.6.1
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  flutter_pdfview: ^1.3.2
  flutter_signin_button: ^2.0.0
  shimmer: ^3.0.0
  google_mobile_ads: ^5.1.0
  awesome_notifications: ^0.9.3+1
  flutter_linkify: ^6.0.0
  syncfusion_flutter_pdfviewer: ^26.2.4
  device_info_plus: ^10.1.0
  universal_io: ^2.2.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  uuid: ^4.4.2
  flutter_colorpicker: ^1.1.0
  photo_view: ^0.15.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  web: ^1.1.0
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  carousel_slider: ^5.0.0
  video_player: ^2.9.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/xerox.png
    - assets/images/defaultimage.png
    - assets/images/groupchat.png
    - assets/images/logo.png
    - assets/images/materials.png
    - assets/images/navigation.png
    - assets/images/marker.png
    - assets/images/transperentlogo.png
    - assets/images/universitynews.jpeg
    - assets/images/busbooking.png
    - assets/images/earnmoney.png
    - assets/images/VIDEOS AND IMAGES.png
    - assets/images/groupicon.png
    - assets/gsheets_credentials.json
    - assets/googleDrive.json
    - assets/images/LeaveForms.png
    - assets/images/shop.png
    - assets/images/mendress.png
    - assets/images/kidsdress.png
    - assets/images/womendress.png