// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWGXGSNfeezkdPHdEpW1iZAWT7ZpYrM-w',
    appId: '1:87807759596:android:18ee9bf6ea5b8ad4db81c9',
    messagingSenderId: '87807759596',
    projectId: 'findany-84c36',
    databaseURL: 'https://findany-84c36-default-rtdb.firebaseio.com',
    storageBucket: 'findany-84c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZHd_nGdO5UjT_A3-x0WROwJJ7B61-dlQ',
    appId: '1:87807759596:ios:dc34de72819c202cdb81c9',
    messagingSenderId: '87807759596',
    projectId: 'findany-84c36',
    databaseURL: 'https://findany-84c36-default-rtdb.firebaseio.com',
    storageBucket: 'findany-84c36.appspot.com',
    androidClientId: '87807759596-in2t1puib00ri4ucu6m6k5f57levmv77.apps.googleusercontent.com',
    iosClientId: '87807759596-95vs04smcs1tqjka3qipd6c14mmiu0ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.findanyFlutter',
  );
}
